using System.Text.Json.Nodes;
using Ultron.Models;

namespace Ultron.Services;

public static class PhoneTools
{
    public static IReadOnlyList<ToolDef> All { get; } = Build();

    private static ToolDef NoArgs(string name, string desc = "") => new()
    {
        Name = name,
        Description = desc,
        Parameters = new JsonObject
        {
            ["type"] = "object",
            ["properties"] = new JsonObject(),
            ["required"] = new JsonArray(),
        },
    };

    private static ToolDef WithArgs(string name, string desc = "", params (string p, string t, bool req)[] args) => new()
    {
        Name = name,
        Description = desc,
        Parameters = new JsonObject
        {
            ["type"] = "object",
            ["properties"] = new JsonObject((IEnumerable<KeyValuePair<string, JsonNode?>>)args.Select(a => new KeyValuePair<string, JsonNode?>(a.p, new JsonObject { ["type"] = a.t }))),
            ["required"] = new JsonArray(args.Where(a => a.req).Select(a => (JsonNode)a.p).ToArray()),
        },
    };

    private static IReadOnlyList<ToolDef> Build()
    {
        var list = new List<ToolDef>
        {
            // POWER (removed dangerous: reboot, shutdown, recovery, bootloader, safe_mode)
            // NoArgs("phone_reboot", "Reboot the phone."),
            // NoArgs("phone_reboot_recovery", "Reboot the phone into recovery mode."),
            // NoArgs("phone_reboot_bootloader", "Reboot the phone into bootloader mode."),
            // NoArgs("phone_shutdown", "Power off the phone."),
            // NoArgs("phone_safe_mode", "Reboot the phone into safe mode."),
            NoArgs("phone_screen_on", "Wake the phone screen."),
            NoArgs("phone_screen_off", "Turn the phone screen off."),
            // SCREEN
            NoArgs("phone_screen_on", "Wake the phone screen."),
            NoArgs("phone_screen_off", "Turn the phone screen off."),
            NoArgs("phone_unlock", "Wake the phone and swipe to unlock (for swipe-only lock screens)."),
            // WithArgs("phone_unlock_pin", "Wake and unlock the phone using the stored PIN.", ("pin", "string", true)),
            WithArgs("phone_screen_brightness", "Set the phone screen brightness (0-255).", ("level", "integer", true)),
            WithArgs("phone_screen_rotation", "Enable or disable auto screen rotation.", ("auto", "boolean", true)),
            WithArgs("phone_screen_rotate", "Rotate the screen to a specific orientation (0/90/180/270).", ("degrees", "integer", true)),
            NoArgs("phone_screenshot", "Take a screenshot of the phone screen and save it locally."),
            WithArgs("phone_screen_record", "Record the phone screen for N seconds (max 180).", ("seconds", "integer", false)),
            // DEVICE
            NoArgs("phone_device_info", "Return brand, model, Android version, resolution, density, battery."),
            NoArgs("phone_battery", "Return battery level, charging status, temperature, voltage, health."),
            // INPUT
            NoArgs("phone_home", "Press the phone home button."),
            NoArgs("phone_back", "Press the phone back button."),
            NoArgs("phone_recent", "Open the recent apps screen."),
            WithArgs("phone_tap", "Tap at absolute screen coordinates.", ("x", "integer", true), ("y", "integer", true)),
            WithArgs("phone_long_press", "Long-press at coordinates.", ("x", "integer", true), ("y", "integer", true), ("duration_ms", "integer", false)),
            WithArgs("phone_swipe", "Swipe between two coordinates.", ("x1", "integer", true), ("y1", "integer", true), ("x2", "integer", true), ("y2", "integer", true)),
            NoArgs("phone_swipe_up"),
            NoArgs("phone_swipe_down"),
            NoArgs("phone_swipe_left"),
            NoArgs("phone_swipe_right"),
            WithArgs("phone_type", "Type text into the phone's focused input field.", ("text", "string", true)),
            WithArgs("phone_type_slow", "Type text character by character, slowly.", ("text", "string", true)),
            WithArgs("phone_key_event", "Send a raw Android keycode (e.g. KEYCODE_ENTER).", ("keycode", "string", true)),
            NoArgs("phone_volume_up"),
            NoArgs("phone_volume_down"),
            NoArgs("phone_volume_mute"),
            WithArgs("phone_set_volume", "Set the media volume level.", ("level", "integer", true)),
            NoArgs("phone_get_volume"),
            // APPS
            WithArgs("phone_open_app", "Open an app by package name or alias (camera/settings/chrome/phone/contacts/messages/gallery/youtube).", ("package", "string", true)),
            WithArgs("phone_close_app", "Force-stop an app by package name.", ("package", "string", true)),
            WithArgs("phone_clear_app_data", "Clear the data of an app.", ("package", "string", true)),
            NoArgs("phone_list_apps", "List all third-party installed apps."),
            NoArgs("phone_list_all_apps", "List all installed apps including system apps."),
            WithArgs("phone_app_info", "Return details about an installed package.", ("package", "string", true)),
            WithArgs("phone_is_app_running", "Check whether an app is currently running.", ("package", "string", true)),
            NoArgs("phone_current_activity", "Return the currently resumed activity/package."),
            // CAMERA
            NoArgs("phone_open_camera", "Open the phone camera app."),
            NoArgs("phone_take_photo", "Take a photo."),
            NoArgs("phone_take_selfie", "Take a selfie with the front camera."),
            NoArgs("phone_toggle_flash", "Toggle the camera flash."),
            NoArgs("phone_switch_camera", "Switch between front and back camera."),
            NoArgs("phone_selfie_verify", "Wake, unlock, and take a verified selfie of the user."),
            WithArgs("phone_record_video", "Record a video for N seconds.", ("seconds", "integer", false)),
            // CLIPBOARD
            NoArgs("phone_get_clipboard", "Read the phone clipboard."),
            WithArgs("phone_set_clipboard", "Set the phone clipboard to text.", ("text", "string", true)),
            WithArgs("phone_share_text", "Open the share dialog with text.", ("text", "string", true)),
            WithArgs("phone_share_file", "Open the share dialog for a file path.", ("path", "string", true)),
            // FILES
            WithArgs("phone_list_files", "List files in a phone directory (default /sdcard/).", ("path", "string", false)),
            NoArgs("phone_list_downloads"),
            NoArgs("phone_list_pictures"),
            NoArgs("phone_list_documents"),
            NoArgs("phone_list_music"),
            NoArgs("phone_list_videos"),
            WithArgs("phone_find_files", "Find files by name.", ("name", "string", true)),
            WithArgs("phone_search_files", "Search files case-insensitively.", ("query", "string", true)),
            WithArgs("phone_delete_file", "Delete a file on the phone.", ("path", "string", true)),
            WithArgs("phone_delete_folder", "Recursively delete a folder on the phone.", ("path", "string", true)),
            WithArgs("phone_file_info", "Return info about a file.", ("path", "string", true)),
            NoArgs("phone_storage_info"),
            WithArgs("phone_pull_file", "Pull a file from the phone to the PC.", ("path", "string", true)),
            WithArgs("phone_push_file", "Push a local file to the phone.", ("local", "string", true), ("remote", "string", false)),
            WithArgs("phone_create_folder", "Create a directory on the phone.", ("path", "string", true)),
            WithArgs("phone_move_file", "Move a file on the phone.", ("src", "string", true), ("dst", "string", true)),
            WithArgs("phone_copy_file", "Copy a file on the phone.", ("src", "string", true), ("dst", "string", true)),
            // SETTINGS
            NoArgs("phone_wifi_on"),
            NoArgs("phone_wifi_off"),
            NoArgs("phone_wifi_status"),
            NoArgs("phone_bluetooth_on"),
            NoArgs("phone_bluetooth_off"),
            NoArgs("phone_bluetooth_status"),
            NoArgs("phone_airplane_on"),
            NoArgs("phone_airplane_off"),
            NoArgs("phone_hotspot_on"),
            NoArgs("phone_hotspot_off"),
            NoArgs("phone_dnd_on"),
            NoArgs("phone_dnd_off"),
            NoArgs("phone_flashlight_on"),
            NoArgs("phone_flashlight_off"),
            NoArgs("phone_location_on"),
            NoArgs("phone_location_off"),
            NoArgs("phone_nfc_on"),
            NoArgs("phone_nfc_off"),
            NoArgs("phone_auto_rotate_on"),
            NoArgs("phone_auto_rotate_off"),
            WithArgs("phone_get_settings", "Return settings from a category (wifi/bluetooth/display/sound/security/all_global/all_system/all_secure).", ("category", "string", true)),
            // NETWORK
            NoArgs("phone_ip_address"),
            WithArgs("phone_ping", "Ping a host from the phone.", ("host", "string", true)),
            NoArgs("phone_wifi_scan"),
            NoArgs("phone_wifi_info"),
            NoArgs("phone_connected_network"),
            // CALLS & SMS
            WithArgs("phone_make_call", "Place a phone call.", ("number", "string", true)),
            NoArgs("phone_answer_call"),
            NoArgs("phone_reject_call"),
            NoArgs("phone_end_call"),
            WithArgs("phone_send_sms", "Send an SMS.", ("number", "string", true), ("message", "string", true)),
            NoArgs("phone_read_sms", "Read recent SMS from the inbox."),
            NoArgs("phone_read_notifications", "Read recent phone notifications."),
            NoArgs("phone_clear_notifications"),
            // CONTACTS & CALENDAR
            NoArgs("phone_list_contacts"),
            WithArgs("phone_search_contacts", "Search contacts by name.", ("name", "string", true)),
            NoArgs("phone_list_calendar"),
            // MEDIA
            NoArgs("phone_media_play"),
            NoArgs("phone_media_pause"),
            NoArgs("phone_media_next"),
            NoArgs("phone_media_previous"),
            NoArgs("phone_media_stop"),
            // SYSTEM (removed dangerous: set_prop, grant/revoke permission)
            NoArgs("phone_system_info"),
            NoArgs("phone_running_processes"),
            NoArgs("phone_disk_usage"),
            WithArgs("phone_logcat", "Return recent logcat entries.", ("lines", "integer", false)),
            // WithArgs("phone_get_prop", "Get an Android system property.", ("prop", "string", true)),
            // WithArgs("phone_set_prop", "Set an Android system property.", ("prop", "string", true), ("value", "string", true)),
            NoArgs("phone_installed_packages"),
            // WithArgs("phone_grant_permission", "Grant a runtime permission to a package.", ("package", "string", true), ("permission", "string", true)),
            // WithArgs("phone_revoke_permission", "Revoke a runtime permission from a package.", ("package", "string", true), ("permission", "string", true)),
            WithArgs("phone_notify", "Post a notification on the phone.", ("title", "string", true), ("message", "string", true)),
            NoArgs("phone_ring", "Ring the phone loudly to locate it."),
            WithArgs("phone_vibrate", "Vibrate the phone for N ms.", ("ms", "integer", false)),
        };
        return list.Select(t => string.IsNullOrEmpty(t.Description)
            ? new ToolDef
            {
                Name = t.Name,
                Description = "Phone control: " + t.Name.Replace("phone_", "").Replace("_", " ") + ".",
                Parameters = t.Parameters,
            }
            : t).ToList();
    }

    public static string Execute(AdbClient p, string name, JsonNode? json)
    {
        var s = (string key) => json?[key]?.GetValue<string>() ?? "";
        var i = (string key, int d) => json?[key]?.GetValue<int>() ?? d;
        var b = (string key, bool d) => json?[key]?.GetValue<bool>() ?? d;
        var ok = () => p.Connect() ? null : "Phone not reachable over ADB.";

        return name switch
        {
            "phone_screen_on" => ok() ?? p.ScreenOn(),
            "phone_screen_off" => ok() ?? p.ScreenOff(),
            "phone_unlock" => ok() ?? p.Unlock(),
            "phone_screen_brightness" => ok() ?? p.ScreenBrightness(i("level", 128)),
            "phone_screen_rotation" => ok() ?? p.ScreenRotation(b("auto", true)),
            "phone_screen_rotate" => ok() ?? p.ScreenRotate(i("degrees", 0)),
            "phone_screenshot" => ok() ?? p.Screenshot(),
            "phone_screen_record" => ok() ?? p.ScreenRecord(i("seconds", 10)),
            "phone_device_info" => ok() ?? p.DeviceInfo(),
            "phone_battery" => ok() ?? p.Battery(),
            "phone_home" => ok() ?? p.Home(),
            "phone_back" => ok() ?? p.Back(),
            "phone_recent" => ok() ?? p.Recent(),
            "phone_tap" => ok() ?? p.Tap(i("x", 0), i("y", 0)),
            "phone_long_press" => ok() ?? p.LongPress(i("x", 0), i("y", 0), i("duration_ms", 1000)),
            "phone_swipe" => ok() ?? p.Swipe(i("x1", 0), i("y1", 0), i("x2", 0), i("y2", 0)),
            "phone_swipe_up" => ok() ?? p.SwipeUp(),
            "phone_swipe_down" => ok() ?? p.SwipeDown(),
            "phone_swipe_left" => ok() ?? p.SwipeLeft(),
            "phone_swipe_right" => ok() ?? p.SwipeRight(),
            "phone_type" => ok() ?? p.TypeText(s("text")),
            "phone_type_slow" => ok() ?? p.TypeTextSlow(s("text")),
            "phone_key_event" => ok() ?? p.KeyEvent(s("keycode")),
            "phone_volume_up" => ok() ?? p.VolumeUp(),
            "phone_volume_down" => ok() ?? p.VolumeDown(),
            "phone_volume_mute" => ok() ?? p.VolumeMute(),
            "phone_set_volume" => ok() ?? p.SetVolume(i("level", 5)),
            "phone_get_volume" => ok() ?? p.GetVolume(),
            "phone_open_app" => ok() ?? p.OpenApp(s("package")),
            "phone_close_app" => ok() ?? p.CloseApp(s("package")),
            "phone_clear_app_data" => ok() ?? p.ClearAppData(s("package")),
            "phone_list_apps" => ok() ?? p.ListApps(),
            "phone_list_all_apps" => ok() ?? p.ListAllApps(),
            "phone_app_info" => ok() ?? p.AppInfo(s("package")),
            "phone_is_app_running" => ok() ?? p.IsAppRunning(s("package")),
            "phone_current_activity" => ok() ?? p.CurrentActivity(),
            "phone_open_camera" => ok() ?? p.OpenCamera(),
            "phone_take_photo" => ok() ?? p.TakePhoto(),
            "phone_take_selfie" => ok() ?? p.TakeSelfie(),
            "phone_toggle_flash" => ok() ?? p.ToggleFlash(),
            "phone_switch_camera" => ok() ?? p.SwitchCamera(),
            "phone_selfie_verify" => ok() ?? p.SelfieVerify(),
            "phone_record_video" => ok() ?? p.RecordVideo(i("seconds", 10)),
            "phone_get_clipboard" => ok() ?? p.GetClipboard(),
            "phone_set_clipboard" => ok() ?? p.SetClipboard(s("text")),
            "phone_share_text" => ok() ?? p.ShareText(s("text")),
            "phone_share_file" => ok() ?? p.ShareFile(s("path")),
            "phone_list_files" => ok() ?? p.ListFiles(s("path")),
            "phone_list_downloads" => ok() ?? p.ListDownloads(),
            "phone_list_pictures" => ok() ?? p.ListPictures(),
            "phone_list_documents" => ok() ?? p.ListDocuments(),
            "phone_list_music" => ok() ?? p.ListMusic(),
            "phone_list_videos" => ok() ?? p.ListVideos(),
            "phone_find_files" => ok() ?? p.FindFiles(s("name")),
            "phone_search_files" => ok() ?? p.SearchFiles(s("query")),
            "phone_delete_file" => ok() ?? p.DeleteFile(s("path")),
            "phone_delete_folder" => ok() ?? p.DeleteFolder(s("path")),
            "phone_file_info" => ok() ?? p.FileInfo(s("path")),
            "phone_storage_info" => ok() ?? p.StorageInfo(),
            "phone_pull_file" => ok() ?? p.PullFile(s("path")),
            "phone_push_file" => ok() ?? p.PushFile(s("local"), string.IsNullOrEmpty(s("remote")) ? "/sdcard/Download/" : s("remote")),
            "phone_create_folder" => ok() ?? p.CreateFolder(s("path")),
            "phone_move_file" => ok() ?? p.MoveFile(s("src"), s("dst")),
            "phone_copy_file" => ok() ?? p.CopyFile(s("src"), s("dst")),
            "phone_wifi_on" => ok() ?? p.WifiOn(),
            "phone_wifi_off" => ok() ?? p.WifiOff(),
            "phone_wifi_status" => ok() ?? p.WifiStatus(),
            "phone_bluetooth_on" => ok() ?? p.BluetoothOn(),
            "phone_bluetooth_off" => ok() ?? p.BluetoothOff(),
            "phone_bluetooth_status" => ok() ?? p.BluetoothStatus(),
            "phone_airplane_on" => ok() ?? p.AirplaneOn(),
            "phone_airplane_off" => ok() ?? p.AirplaneOff(),
            "phone_hotspot_on" => ok() ?? p.HotspotOn(),
            "phone_hotspot_off" => ok() ?? p.HotspotOff(),
            "phone_dnd_on" => ok() ?? p.DndOn(),
            "phone_dnd_off" => ok() ?? p.DndOff(),
            "phone_flashlight_on" => ok() ?? p.FlashlightOn(),
            "phone_flashlight_off" => ok() ?? p.FlashlightOff(),
            "phone_location_on" => ok() ?? p.LocationOn(),
            "phone_location_off" => ok() ?? p.LocationOff(),
            "phone_nfc_on" => ok() ?? p.NfcOn(),
            "phone_nfc_off" => ok() ?? p.NfcOff(),
            "phone_auto_rotate_on" => ok() ?? p.AutoRotateOn(),
            "phone_auto_rotate_off" => ok() ?? p.AutoRotateOff(),
            "phone_get_settings" => ok() ?? p.GetSettings(s("category")),
            "phone_ip_address" => ok() ?? p.IpAddress(),
            "phone_ping" => ok() ?? p.Ping(s("host")),
            "phone_wifi_scan" => ok() ?? p.WifiScan(),
            "phone_wifi_info" => ok() ?? p.WifiInfo(),
            "phone_connected_network" => ok() ?? p.ConnectedNetwork(),
            "phone_make_call" => ok() ?? p.MakeCall(s("number")),
            "phone_answer_call" => ok() ?? p.AnswerCall(),
            "phone_reject_call" => ok() ?? p.RejectCall(),
            "phone_end_call" => ok() ?? p.EndCall(),
            "phone_send_sms" => ok() ?? p.SendSms(s("number"), s("message")),
            "phone_read_sms" => ok() ?? p.ReadSms(),
            "phone_read_notifications" => ok() ?? p.ReadNotifications(),
            "phone_clear_notifications" => ok() ?? p.ClearNotifications(),
            "phone_list_contacts" => ok() ?? p.ListContacts(),
            "phone_search_contacts" => ok() ?? p.SearchContacts(s("name")),
            "phone_list_calendar" => ok() ?? p.ListCalendar(),
            "phone_media_play" => ok() ?? p.MediaPlay(),
            "phone_media_pause" => ok() ?? p.MediaPause(),
            "phone_media_next" => ok() ?? p.MediaNext(),
            "phone_media_previous" => ok() ?? p.MediaPrevious(),
            "phone_media_stop" => ok() ?? p.MediaStop(),
            "phone_system_info" => ok() ?? p.SystemInfo(),
            "phone_running_processes" => ok() ?? p.RunningProcesses(),
            "phone_disk_usage" => ok() ?? p.DiskUsage(),
            "phone_logcat" => ok() ?? p.Logcat(i("lines", 20)),
            // "phone_get_prop" => ok() ?? p.GetProp(s("prop")),
            // "phone_set_prop" => ok() ?? p.SetProp(s("prop"), s("value")),
            "phone_installed_packages" => ok() ?? p.InstalledPackages(),
            // "phone_grant_permission" => ok() ?? p.GrantPermission(s("package"), s("permission")),
            // "phone_revoke_permission" => ok() ?? p.RevokePermission(s("package"), s("permission")),
            "phone_notify" => ok() ?? p.Notify(s("title"), s("message")),
            "phone_ring" => ok() ?? p.RingPhone(),
            "phone_vibrate" => ok() ?? p.Vibrate(i("ms", 500)),
            _ => "That phone tool is not available.",
        };
    }
}