name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Unit tests
        run: dotnet test tools/Tests/Ultron.Tests.csproj --no-restore

      - name: Build app
        run: dotnet build --no-restore --no-dependencies -c Debug